use topcoat::{
    Result,
    context::Cx,
    runtime::Event,
    view::{Attributes, Child, View, ViewExt, attributes, class, component, view},
};

/// Connect a trigger button to a dropdown menu using the browser's Popover API.
///
/// `id` must be a trusted DOM identifier generated by the caller.
pub fn anchored_menu_trigger_attributes(cx: &Cx, id: &str) -> Attributes {
    let anchor = format!("anchor-name: --gr-{id}");
    attributes! { cx =>
        popovertarget=(id)
        popovertargetaction="toggle"
        aria-controls=(id)
        style=(anchor)
    }
}

#[doc = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/docs/en/components/anchored-menu.md"
))]
#[component]
pub async fn anchored_menu(
    cx: &Cx,
    id: &str,
    label: &str,
    #[default] mut attrs: Attributes,
    #[default] child: Child<'_>,
) -> Result<impl View> {
    let anchor = format!("position-anchor: --gr-{id}");
    let close_id = id.to_owned();
    let caller_class = attrs.remove("class");
    let panel_class = class!(
        "gr-anchored-menu fixed inset-auto m-0 mt-1.5 min-w-[180px] rounded-lg border border-[#f0f0f0] bg-white p-1.5 font-mono text-[13px] text-[#262626] shadow-lg",
        caller_class,
    );
    let semantics = attributes! { cx =>
        id=(id)
        class=(panel_class)
        popover="auto"
        role="group"
        aria-label=(label)
        style=(anchor)
        @click=$(move |_event: Event| {
            let _id = close_id.to_owned();
            raw!("document.getElementById(${_id}.dehydrate())?.hidePopover()", ());
        })
    };
    attrs.extend(semantics);

    Ok(view! { <div (attrs)>(child)</div> }.boxed())
}
