use topcoat::{
    Result,
    context::Cx,
    icon::icon,
    runtime::{Event, Signal},
    view::{Attributes, Child, View, ViewExt, attributes, class, component, view},
};

use crate::UiLanguage;
use crate::icons::CLOSE_OUTLINED;

/// Stable dialog ID, title, and optional eyebrow.
#[derive(Clone, Copy)]
pub struct DialogConfig<'a> {
    id: &'a str,
    title: &'a str,
    eyebrow: Option<&'a str>,
}

impl<'a> DialogConfig<'a> {
    /// Create a dialog configuration.
    pub const fn new(id: &'a str, title: &'a str) -> Self {
        Self {
            id,
            title,
            eyebrow: None,
        }
    }

    /// Show a short context label above the title.
    pub const fn with_eyebrow(mut self, eyebrow: &'a str) -> Self {
        self.eyebrow = Some(eyebrow);
        self
    }
}

/// Create button attributes that open a native modal dialog.
///
/// `id` must be a trusted DOM identifier generated by the caller, not unchecked user input.
pub fn dialog_trigger_attributes(cx: &Cx, id: &str) -> Attributes {
    attributes! { cx =>
        commandfor=(id)
        command="show-modal"
        aria-haspopup="dialog"
        aria-controls=(id)
    }
}

/// Create button attributes that close the specified dialog.
pub fn dialog_close_attributes(cx: &Cx, id: &str) -> Attributes {
    attributes! { cx =>
        commandfor=(id)
        command="close"
    }
}

#[doc = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/docs/en/components/dialog.md"
))]
#[component]
pub async fn dialog(
    cx: &Cx,
    config: DialogConfig<'_>,
    busy: &Signal<bool>,
    #[default] language: UiLanguage,
    #[default] mut attrs: Attributes,
    #[default] child: Child<'_>,
) -> Result<impl View> {
    let DialogConfig { id, title, eyebrow } = config;
    let title_id = format!("{id}-title");
    let close = dialog_close_attributes(cx, id);
    let prevent_cancel = busy.clone();
    let caller_class = attrs.remove("class");
    let root_class = class!(
        "gr-dialog m-auto max-h-[calc(100dvh_-_48px)] w-[min(580px,calc(100%_-_32px))] overflow-hidden rounded-[10px] border border-[#f0f0f0] bg-white p-0 text-left font-mono text-[#262626] shadow-[0_18px_60px_rgba(0,0,0,0.2)]",
        caller_class,
    );
    attrs.extend(attributes! { cx =>
        id=(id)
        class=(root_class)
        role="dialog"
        aria-modal="true"
        aria-labelledby=(title_id.as_str())
        @cancel=$(move |event: Event| {
            if prevent_cancel.get() {
                event.prevent_default();
            }
        })
    });

    // 缩小父级 ThenView 的状态，避免嵌套弹窗渲染时产生大型栈临时值。
    Ok(view! {
        <dialog (attrs)>
            <header class="gr-dialog-header flex shrink-0 items-start justify-between gap-4 border-b border-[#f0f0f0] px-6 pb-[18px] pt-[22px] max-[640px]:px-[18px]">
                <div class="min-w-0">
                    if let Some(eyebrow) = eyebrow {
                        <p class="m-0 text-xs font-bold tracking-[0.08em] text-[#8c8c8c]">(eyebrow)</p>
                    }
                    <h2 class="mb-0 mt-1 text-xl font-semibold leading-7" id=(title_id.as_str())>(title)</h2>
                </div>
                <button class="inline-flex size-8 shrink-0 cursor-pointer items-center justify-center rounded-md border-0 bg-transparent p-0 text-[rgba(0,0,0,0.45)] transition-colors duration-200 hover:bg-[rgba(0,0,0,0.06)] hover:text-[rgba(0,0,0,0.88)] focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-[#91caff]" type="button" (close) :disabled=$(busy.get()) aria-label=(language.select("Close", "关闭"))>
                    icon(data: CLOSE_OUTLINED, size: 16)
                </button>
            </header>
            (child)
        </dialog>
    }.boxed())
}
